name: AccuKnox Scan Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  accuknox-cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main  
   
      - name: Run AccuKnox CSPM Scan
        uses: 'accuknox/container-scan-action@v0.0.1'
        with:
          token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzEwOTQ1NzIwLCJqdGkiOiIxODdjNTA2NmZlYjY0YmNiOWM4MTgzNDZhODRiMzg0NSIsImlzcyI6ImNzcG0uZGVtby5hY2N1a25veC5jb20ifQ.DkgKXqHg1iBsqqxUWEgvYwk8qcwWeRouEJzARu9gCEBfWcLWtnthhLk_enJDaK9R82vTRfgejnIIaIQp--u8qV0MWfCx6DCaZbvxemwcXuHMkgpmZUo7ZfR0aiWX3eB_ZIy7kqsNRkbcVyIBJcTYXAxgp7HNMTDIYXhJSQ6E61jxnmUXlh7_4-_CaLhvoCZRRl_Ij9h39nwLn5IzRcwTtAcyW7F_CqnAsm6vX8jWkuAGqM0kdw2P06AkD8N6Dxys1lwDBGHt2P9JzruQHiXUA23IRRHfNOiXSiW_WYvm2MyFMF26z3mnzDmkCxIjdEUseYv2Nzd3-a27fDt7ytfsig"
          repository_name: "udit-uniyal/accuknox-container-scan-example"
          tenant_id: "167"
          severity: "HIGH"


         
